openapi: 3.0.0
info:
  title: NovaPrime Wasabi API
  version: 1.0.0

servers:
  - url: https://novaprime-backend.onrender.com

paths:
  /:
    get:
      summary: Root health check
      operationId: root
      responses:
        "200":
          description: Server is live
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /upload_stats:
    post:
      summary: Upload user stats to Wasabi
      operationId: uploadStats
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                stats:
                  type: object
              required:
                - user_id
                - stats
      responses:
        "200":
          description: Stats successfully uploaded
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

  /get_user_stats:
    post:
      summary: Retrieve a user's stats from Wasabi
      operationId: getUserStats
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
              required:
                - user_id
      responses:
        "200":
          description: Stats successfully retrieved
          content:
            application/json:
              schema:
                type: object

  /list_all_user_ids:
    get:
      summary: List all user IDs from Wasabi
      operationId: listAllUserIds
      responses:
        "200":
          description: List of user IDs
          content:
            application/json:
              schema:
                type: object

  /get_all_user_stats:
    get:
      summary: Retrieve all user stats from Wasabi
      operationId: getAllUserStats
      responses:
        "200":
          description: All user stats returned
          content:
            application/json:
              schema:
                type: object

  /openapi.yaml:
    get:
      summary: Serve OpenAPI specification
      operationId: serveOpenapi
      responses:
        "200":
          description: OpenAPI spec file
          content:
            text/yaml:
              schema:
                type: string
